import { cookies } from "next/headers";
import AppWrapper from "./components/AppWrapper";
import { SocketProvider } from "./components/SocketProvider";
import { UserProvider } from "./components/UserProvider";
import "./globals.css";
import { getUserIdFromToken } from "./lib/JWTVeriify";

export const metadata = {
  title: "Расскажи и ...",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("accessToken")?.value;
  const userId = await getUserIdFromToken(accessToken || "");
  return (
    <html lang="ru">
      <body>
        <UserProvider userId={userId}>
          <SocketProvider token={accessToken}>
            <AppWrapper>{children}</AppWrapper>
          </SocketProvider>
        </UserProvider>
      </body>
    </html>
  );
}
