import { jwtVerify } from "jose";
import { cookies } from "next/headers";
import AppWrapper from "./components/AppWrapper";
import { SocketProvider } from "./components/SocketProvider";
import { UserProvider } from "./components/UserProvider";
import "./globals.css";

export const metadata = {
  title: "WhatsApp Clone",
  description: "Generated by create next app",
};

async function getUserIdFromToken(token: string): Promise<string | null> {
  if (!token) return null;

  const secret = process.env.JWT_SECRET;
  if (!secret) {
    console.error("JWT_SECRET is not set in environment variables.");
    throw new Error("JWT_SECRET is not configured.");
  }

  try {
    const secretKey = new TextEncoder().encode(secret);
    const { payload } = await jwtVerify(token, secretKey);
    return payload.sub || null;
  } catch (error) {
    // Логируем ошибку для отладки, но не выводим ее пользователю
    console.error("JWT verification failed:", error);
    return null; // Не удалось верифицировать, значит токен невалиден
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("accessToken")?.value;
  const userId = await getUserIdFromToken(accessToken || "");

  return (
    <html lang="ru">
      <body>
        <UserProvider userId={userId}>
          <SocketProvider token={accessToken}>
            <AppWrapper>{children}</AppWrapper>
          </SocketProvider>
        </UserProvider>
      </body>
    </html>
  );
}
