import { jwtVerify } from "jose";
import { cookies } from "next/headers";
import AppWrapper from "./components/AppWrapper";
import { SocketProvider } from "./components/SocketProvider";
import { UserProvider } from "./components/UserProvider";
import "./globals.css";

export const metadata = {
  title: "WhatsApp Clone",
  description: "Generated by create next app",
};

async function getUserIdFromToken(token: string): Promise<string | null> {
  if (!token) return null;
  try {
    const secret = new TextEncoder().encode(
      process.env.JWT_SECRET || "super-secret-key",
    );
    const { payload } = await jwtVerify(token, secret);
    return payload.sub || null;
  } catch {
    return null; // Не удалось верифицировать, значит токен невалиден
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("accessToken")?.value;
  const userId = await getUserIdFromToken(accessToken || "");

  return (
    <html lang="ru">
      <body>
        <UserProvider userId={userId}>
          <SocketProvider token={accessToken}>
            <AppWrapper>{children}</AppWrapper>
          </SocketProvider>
        </UserProvider>
      </body>
    </html>
  );
}
